name: Deploy static root and migration app to GitHub Pages

on:
  push:
    branches: [ main, React_Migration ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build static root (from static-root/ folder)
        run: |
          mkdir -p ./out
          if [ -d static-root ]; then
            cp -r static-root/* ./out/
          else
            echo "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>InteractiveCV</title></head><body><h1>Root site not found</h1><p>Create a <code>static-root/</code> folder with your static site (HTML/CSS/JS) to publish at /InteractiveCV/.</p></body></html>" > ./out/index.html
          fi

      - name: Build migration React app
        env:
          VITE_DEPLOY_SUBPATH: migration
        run: npm run build:migration

      - name: Stage migration app under subfolder
        run: |
          mkdir -p ./out/migration
          cp -r dist/* ./out/migration/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


